name: Run Playwright Pytest Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04   # Обязательно 22.04, чтобы не было проблем с deps

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          source venv/bin/activate
          playwright install --with-deps

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest --alluredir=reports/allure-results

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          allure_results: reports/allure-results
          allure_report: reports/allure-report
          gh_pages: false

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report
